import type {Metadata} from "next";
import {Mulish} from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/layout/Navbar";
import {ThemeProvider} from "@/app/theme-provider";
import Footer from "@/components/layout/Footer";
const font = Mulish({subsets: ["latin"]});
import {
    ClerkProvider,
    SignInButton,
  SignedIn,
  SignedOut,
  UserButton
  } from '@clerk/nextjs'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <ClerkProvider>
            <html lang="en" className="dark">
            <body className={font.className}>
                <ThemeProvider>
                    <Navbar/>
                    {children}
                    {/* <Footer/> */}
                </ThemeProvider>
            </body>
        </html>

        </ClerkProvider>
    );
}
